name: BookExploitFix
version: 0.15
main: me.minoneer.bukkit.bookexploit.BookExploitFix
author: minoneer
description: Fixes an exploit with JSON books
website: 'https://www.spigotmc.org/resources/bookexploitfix.5897/build/'
commands:
  filter:
    aliases: [bookfilter, filterbook]
    usage: /<command>
    permission: bookfilter.filter
